# Generated by Django 3.1.3 on 2020-11-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdetails',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='empdetails',
            name='empid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empdetails',
            name='fname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='empdetails',
            name='lname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='empdetails',
            name='pnum',
            field=models.IntegerField(default=0),
        ),
    ]
