# Generated by Django 3.1.3 on 2020-11-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subems', '0002_auto_20201119_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField(default=0)),
                ('fname', models.CharField(default='', max_length=20)),
                ('lname', models.CharField(default='', max_length=20)),
                ('pnum', models.CharField(default=0, max_length=10)),
                ('email', models.EmailField(default='', max_length=50)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.DeleteModel(
            name='empdetails',
        ),
    ]
