# Generated by Django 3.1.3 on 2020-11-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subems', '0003_auto_20201119_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pnum',
            field=models.CharField(max_length=10),
        ),
    ]
